config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }, controllers: {
  sessions: 'users/sessions'
  }

  resources :tests, only: :index do
    resources :questions, only: :index, shallow: true, except: :index do
      resources :answers, only: :index, shallow: true, except: :index
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, expect: :index do
        resources :answers, shallow: true, expect: :index
      end
    end
    resources :gists, only: :index
    resources :badges    
  end

  resources :feedbacks, only: %i[new create]
  resources :badges, only: :index
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :users_badges
  has_many :users, through: :users_badges

  before_save :set_default_image_path, unless: :image_path?

  validates :title, :image_path, :rule_value, presence: true
  validates :rule, presence: true, uniqueness: { scope: :rule_value }
  validates :rule, inclusion: { in: BadgeService::BADGES_TYPE }

  def self.images
    images_path = 'app/assets/images/'
    badges = Dir.glob("#{images_path}badges/*")
    badges.map { |badge_path| badge_path.gsub(images_path, '') }
  end

  private

  def set_default_image_path
    self.image_path = 'badges/badge-default.png'
  end
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :authenticate_user!
  before_action :find_badges, only: :index
  before_action :find_badge, only: %i[show edit update destroy]

  def index; end

  def new
    @badge = Badge.new
  end

  def edit; end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badges_path, notice: t('admin.created', resource: @badge.model_name.human)
    else
      render :new
    end
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badges_path, notice: t('admin.updated', resource: @badge.model_name.human)
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy

    redirect_to admin_badges_path, notice: t('admin.deleted', resource: @badge.model_name.human)
  end

  private

  def find_badges
    @badges = Badge.all
  end

  def find_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:title,
                                  :image_path,
                                  :rule,
                                  :rule_value)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :authenticate_user!

  def index
    @available_badges = Badge.all
    @user_badges = current_user.badges
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
  def rules_for_select
    BadgeService::BADGES_TYPE.map { |rule| I18n.t(:rules)[rule.to_sym] }
  end
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td><%= image_tag badge.image_path, size: "32x32"%></td>
  <td><%= badge.title %></td>
  <td><%= badge.rule %></td>
  <td><%= link_to t('.show'), admin_badge_path(badge) %></td>
  <td><%= link_to t('.edit'), edit_admin_badge_path(badge) %></td>
  <td>
    <%= link_to t('.delete'),
                admin_badge_path(badge),
                method: :delete,
                data: { confirm: t('.delete_confirmation') } %>
  </td>
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge], local: true do |form| %>
  <%= render 'shared/errors', resource: @badge %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title, id: :badge_title, class: "form-control" %>
    </p>
    <p>
      <%= form.label :image %><br>
      <%= form.select :image_path,
                    options_for_select(Badge.images),
                    class: "form-control" %>
    </p>
    <p>
      <%= form.label :rule %><br>
      <%= form.select :rule,
                    rules_for_select,
                    {prompt: 'Выбрать из списка'},
                    class: "form-control rule" %>
    </p>
  <p>
  <fieldset disabled="disabled" class="fieldset_level">
    <%= form.number_field :level, id: :test_level, class: "form-conrtrol" %><br>
  </fieldset>
  </p>
  <p>
  <fieldset disabled="disabled" class="fieldset_category">
    <%= form.collection_select :category_id, Category.all, :id, :title, prompt: true, class: "form-control" %>
  </fieldset>
  </p>
    <p>
    <%= form.submit class: "btn btn-primary" %>
    </p>
<% end %>

app/views/admin/badges/edit.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-4">
    <h1><%= t('.header', title: @badge.title) %></h1>
    <div class="card border-primary">
      <div class="card-body">
        <%= render 'form' %>
        <%= link_to t('.back'), admin_badges_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/badges/index.html.erb
<div class="row justify-content-center mt-3">
<h1><%= t('.header') %></h1>
</div>

<%= render 'shared/errors', resource: @test %>

<div class="row justify-content-center">
  <div class="align-item-center col col-md-8">
    <%= link_to t('.new_badge'), new_admin_badge_path %>

    <table class="table">
      <thead>
        <th><%= t('.image_path') %></th>
        <th><%= t('.title') %></th>
        <th><%= t('.rule') %></th>
        <th colspan="3"><%= t('.actions') %></th>
      </thead>

      <tbody>
        <%= render @badges %>
      </tbody>
    </table>

app/views/admin/badges/new.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-6">
    <h1><%= t('.header') %></h1>
    <div class="card border-primary">
      <div class="card-body">
        <%= render 'form' %>
        <%= link_to t('.back'), admin_badges_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/badges/show.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-6">
    <h2><%= t('.title', badge_title: @badge.title) %></h2>
<p>
  <%= link_to t('.edit') , edit_admin_badge_path(@badge) %>
  <%= link_to t('.back') , admin_badges_path %>
</p>
    <%= image_tag @badge.image_path, title: @badge.title %>
    <p><%= t('.rule') %></p>
  </div>
</div>