config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }, controllers: {
  sessions: 'users/sessions'
  }

  resources :tests, only: :index do
    resources :questions, only: :index, shallow: true, except: :index do
      resources :answers, only: :index, shallow: true, except: :index
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, expect: :index do
        resources :answers, shallow: true, expect: :index
      end
    end
    resources :gists, only: :index
    resources :badges    
  end

  resources :feedbacks, only: %i[new create]
  resources :badges, only: :index
end

app/models/admin.rb
class Admin < User
  validates :first_name, :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  #validate :validate_max_answers, on: :create

  scope :correct, -> { where(correct: true)}

  private

  def validate_max_answers
    errors.add(:body) if @question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :users_badges
  has_many :users, through: :users_badges

  before_save :set_default_image_path, unless: :image_path?

  validates :title, :image_path, :rule_value, presence: true
  validates :rule, presence: true, uniqueness: { scope: :rule_value }
  validates :rule, inclusion: { in: BadgeService::BADGES_TYPE }

  def self.images
    images_path = 'app/assets/images/'
    badges = Dir.glob("#{images_path}badges/*")
    badges.map { |badge_path| badge_path.gsub(images_path, '') }
  end

  private

  def set_default_image_path
    self.image_path = 'badges/badge-default.png'
  end
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope { order(title: :asc) }

  has_many :tests, dependent: :nullify

  validates :title, presence: true
end

app/models/feedback.rb
class Feedback
  include ActiveModel::Model

  attr_accessor :email, :title, :body

  validates_presence_of :title, :email, :body
  validates_format_of :email, with: /.+@.+/
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question

  def hash
    url.split("/").last
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :test_passages, dependent: :destroy, class_name: 'TestPassage', foreign_key: 'current_question_id'

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :user
  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages

  scope :level, ->(level) { where(level: level) }
  scope :easy, -> { level(0..1) }
  scope :medium, -> { level(2..4) }
  scope :hard, -> { level(5..Float::INFINITY) }

  scope :by_category, ->(title) { joins(:category).where(categories: { title: title }) }
  scope :by_level, ->(level) { where(level: level) }

  scope :with_category, -> { where(id: with_qiestions.pluck(:id)).joins(categories: {title: category}) }
  scope :with_questions, -> { joins(:questions).distinct}

  validates :title, presence: true
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :title, uniqueness: { scope: :level }
  validates :time_limit, numericality: { only_integer: true, greater_than_or_equal_to: 1 }

  def self.titles_by_category(name)
    by_category(name).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_save :before_save_find_question

  def test_passed?
    result_percent >= 85
  end

  def result_percent
    (100 * self.correct_question) / test.questions.count
  end

  def accept!(answer_ids)
    self.correct_question += 1 if correct_answer?(answer_ids)
    self.passed = true if test_passed?
    self.current_question = nil if time_out?

    save!
  end

  def current_question_number
    completed_questions.count + 1
  end

  def completed?
    current_question.nil?
  end

  def time_limit_test?
    test.time_limit.present?
  end

  def remaining_seconds
    ((created_at + test.time_limit.minutes) - Time.current).to_i
  end

  def time_out?
    (created_at + test.time_limit.minutes < Time.current) if time_limit_test?
  end

  private


  def correct_answer?(answer_ids)
    correct_answers.ids.sort == Array(answer_ids).map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def before_save_find_question
    if current_question.nil?
      self.current_question = test.questions.first if test.present?
    else
      self.current_question = next_question
    end
  end

  def completed_questions
    test.questions.order(:id).where('id < ?', current_question.id)
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/models/tests_user.rb
class TestsUser < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/user.rb
class User < ApplicationRecord

  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages
  has_many :created_tests, class_name: 'Test', foreign_key: 'user_id', dependent: :destroy
  has_many :gists, dependent: :destroy
  has_many :users_badges
  has_many :badges, through: :users_badges  

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  def tests_by_level(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test: test)
  end

  def admin?
    is_a?(Admin)
  end
end

app/models/users_badge.rb
class UsersBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_test, only: %i[start]
  before_action :find_user, only: :start
  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_test_not_found

  def index
    @tests = Test.all
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end

  def find_user
    @user = User.first
  end

  def rescue_with_test_not_found
    render plain: 'Resource is not found.'
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  FLASH_TYPES = {
    alert: 'warning',
    notice: 'info'
  }.freeze

  def current_year
    Time.current.year
  end

  def github_url(author, repo)
    link_to repo, "https://github.com/#{author}/#{repo}"
  end

  def flash_messages
    safe_join(flash.map { |type, message| content_tag :p, message.html_safe, class: flash_type(type), role: 'alert' })
  end

  def flash_type(type)
    "alert alert-#{FLASH_TYPES[type.to_sym]}"
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
  def rules_for_select
    BadgeService::BADGES_TYPE.map { |rule| I18n.t(:rules)[rule.to_sym] }
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      "Creating a new question for test #{question.test.title}"
    else
      "Edit question for test #{question.test.title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
  def test_header(test)
    if test.new_record?
      t('.create')
    else
      t('.update')
    end
  end

  def test_time_limit(test)
    test.time_limit ? t('.time_limit', time: test.time_limit) : t('.unlimited')
  end
end

app/views/admin/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to 'TestGuru Admin Panel' , root_path, class: 'navbar-brand' %>
  <%= link_to 'Gists', admin_gists_path, class: 'nav-link' %>
  <%= link_to 'Badges', admin_badges_path, class: 'nav-link' %>

  <span class="navbar-text">
    <%= t('.welcome') %>, <b class="nav-admin user-email"><%= current_user.email %></b> Guru |
    <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'text-primary' %>
  </span>
</nav>

app/views/layouts/_footer.html.erb
<footer>
  <p><%= current_year %> | Wolhaa | <%= github_url('Wolhaa', 'test_guru') %></p>
  <p>Project test_guru | <%= link_to t('.feedback'), new_feedback_path %></p>
  <p><%= link_to 'Educational project in the online school Thinknetica', 'http://thinknetica.com/' %></p>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>
  <%= link_to 'Badges', badges_path, class: 'nav-item nav-link' %>  

  <span class="navbar-text">
    <% if user_signed_in? %>
      Welcome, <b><%= current_user.email %></b> Guru |
      <%= link_to 'Logout', destroy_user_session_path, method: :delete %>|
    <% else %>
      <%=link_to "Log in", new_user_session_path, class: 'text-primary' %> |
      <%=link_to "Sing up", new_user_registration_path, class: 'text-primary' %>
    <% end %>
  </span>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin Panel | TestGuru</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'admin/nav' %>
    <div class="container">
      <%= flash_messages %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <mata name="viewport" content="width=device-widrailsth, initial-scale=1, shrink-to-fit=no">

    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>


      <%= flash_messages %>
      <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
  <div>
    <h2><%= t('.header', count: resource.errors.count) %></h2>
      <ul>
        <% resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  </div>
  <% end %>
<% end %>