config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }, controllers: {
  sessions: 'users/sessions'
  }

  resources :tests, only: :index do
    resources :questions, only: :index, shallow: true, except: :index do
      resources :answers, only: :index, shallow: true, except: :index
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, expect: :index do
        resources :answers, shallow: true, expect: :index
      end
    end
    resources :gists, only: :index
    resources :badges    
  end

  resources :feedbacks, only: %i[new create]
  resources :badges, only: :index
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :test_passages, dependent: :destroy, class_name: 'TestPassage', foreign_key: 'current_question_id'

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_save :before_save_find_question

  def test_passed?
    result_percent >= 85
  end

  def result_percent
    (100 * self.correct_question) / test.questions.count
  end

  def accept!(answer_ids)
    self.correct_question += 1 if correct_answer?(answer_ids)
    self.passed = true if test_passed?
    self.current_question = nil if time_out?

    save!
  end

  def current_question_number
    completed_questions.count + 1
  end

  def completed?
    current_question.nil?
  end

  def time_limit_test?
    test.time_limit.present?
  end

  def remaining_seconds
    ((created_at + test.time_limit.minutes) - Time.current).to_i
  end

  def time_out?
    (created_at + test.time_limit.minutes < Time.current) if time_limit_test?
  end

  private


  def correct_answer?(answer_ids)
    correct_answers.ids.sort == Array(answer_ids).map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def before_save_find_question
    if current_question.nil?
      self.current_question = test.questions.first if test.present?
    else
      self.current_question = next_question
    end
  end

  def completed_questions
    test.questions.order(:id).where('id < ?', current_question.id)
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_test_passage, only: %i[show update result gist]

  def show; end

  def result; end

  def gist
    service = GistQuestionService.new(@test_passage.current_question)
    response = service.call

    gist_url = response.html_url
    gist_link = view_context.link_to(gist_url, gist_url, target: :blank)

    if service.status_ok?
      create_gist!(gist_url)
      flash[:notice] = t('.success', url: gist_link)
    else
      flash[:alert] = t('.failed')
    end

    redirect_to @test_passage
  end

  def update
    if params[:answer_ids].nil?
      redirect_to result_test_passage_path(@test_passage)
    else
      @test_passage.accept!(params[:answer_ids])
      if @test_passage.completed?
        @badges = BadgeService.new(@test_passage).give_badges
        @test_passage.user.badges.push(@badges) if @badges.present?

        TestsMailer.completed_test(@test_passage).deliver_now
        redirect_to result_test_passage_path(@test_passage)
      else
        render :show
      end
    end
  end


  private

  def find_test_passage
    @test_passage = TestPassage.find(params[:id])
  end

  def create_gist!(gist_url)
    current_user.gists.create(question: @test_passage.current_question, url: gist_url)
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def show_result_message(test_passage)
    fail = test_passage.time_out? ? t('test_passings.result.time_failed') : t('test_passings.result.failed')
    test_passage.test_passed? ? t('.success') : fail
  end

  def result_color(test_passing)
    test_passing.test_passed? ? 'text-success' : 'text-danger'
  end

  def show_timer(test_passage)
    ((test_passage.created_at + test_passage.test.time_limit.minutes) - Time.current).to_i
  end
end

app/views/test_passages/_timer.html.erb
<%= content_tag :span,
                '',
                class: 'test-timer text-danger',
                data: { time_limit:  @test_passage.remaining_seconds }
%>

app/views/test_passages/result.html.erb
<h1><%= t('.header', title: @test_passage.test.title) %></h1>

<h2 class="<%= result_color(@test_passage) %>">
 <%= show_result_message(@test_passage)%></h2><br>

<p><%= link_to t('.back'), tests_path %></p>

app/views/test_passages/show.html.erb
<h1><%= t('.header', title: @test_passage.test.title) %></h1>
<p>
  <%= render 'timer' %>
</p>

<b>
  <%= @test_passage.current_question.body %>
</b>

<div class="progress">
  <%= content_tag :div,
                  class: 'progress-bar',
                  data: {
                    question_number: @test_passage.current_question_number,
                    questions_count: @test_passage.test.questions.count
                  } do %>
    <%= t('.question_number', q_number: @test_passage.current_question_number, q_count: @test_passage.test.questions.count) %>
  <% end %>
</div>

<%= form_with url: test_passage_path(@test_passage), local: true, id: 'test-passage-form', method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>
      <%= b.label %>
    </p>
  <% end %>
  <p><%= link_to 'Gist Question', gist_test_passage_path(@test_passage), method: :post %></p>
  <p><%= form.submit t('.next') %></p>
<% end %>